### PR TITLE
Recompile libdxcompiler.so to remove depencency on libtinfo.so

### PR DESCRIPTION
**Pull request by expenses**
At the moment, attempting to run kajiya on my arch linux install (on https://github.com/EmbarkStudios/kajiya/pull/46) fails with:

```
A turbosloth LazyWorker "kajiya_backend::shader_compiler::CompileShader" failed

Caused by:
    Failed to load library "./libdxcompiler.so": DlOpen { desc: "libtinfo.so.5: cannot open shared object file: No such file or directory" }
```

Running `ldd libdxcompiler.so` lists the following dynamic library dependencies:
```
        linux-vdso.so.1 (0x00007ffc0df9b000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f28f59e1000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f28f59da000)
	libtinfo.so.5 => not found
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f28f59b9000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f28f599f000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f28f585b000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f28f5643000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f28f5628000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f28f545c000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f28f710d000)
```

The missing one, `libtinfo.so.5` is not installable on arch. The `core/ncurses` package (version `6.3-1`) provided `libtinfo.6`, but this newer version is not compatible. This library is literally only used for the `terminalHasColors` function and is useless in `libdxcompiler.so` which should not be printing anything. The solution to this is to either bundle `libtinfo.5` which is gross, or to recompile `libdxcompiler.so`  without terminfo like so:

```
git clone https://github.com/Microsoft/DirectXShaderCompiler --recursive
cd DirectXShaderCompiler
mkdir build
cd build
cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_TERMINFO=OFF -C ../cmake/caches/PredefinedParams.cmake
ninja
```

The generated library no longer depends on it:

```
        linux-vdso.so.1 (0x00007ffdea17a000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f0ba0958000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f0ba0951000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f0ba0930000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f0ba0916000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f0ba0700000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f0ba05bc000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f0ba059f000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f0ba03d3000)
	/usr/lib64/ld-linux-x86-64.so.2 (0x00007f0ba24e4000)
```

The compiled library is a bit bigger, but I believe that is because the original one was compiled on Windows or something along those lines.

Instead of merging in random binaries it might be better for someone at Embark to recompile it themselves.

### CODE REVIEW

**Comment by h3r2tic** [comment]
Thanks for pointing this out and showing how to fix the issue! Building it on Linux looks way easier than on Windows xD

Hmm... maybe it would be possible to set up some automated CI process to do this because you're quite right about checking in fat binaries.

Regarding `libtinfo.so.5`, have you tried https://aur.archlinux.org/packages/ncurses5-compat-libs? I think I may have used it on Arch last time I was testing it.

Also, is the binary in this PR a fully stripped one? That's quite a big size difference :o
(That being said, Unreal ships with a 600MB `libdxcompiler.so`, so what is a 7MB diff 🤷🤣)

**Comment by expenses** [comment]
I copied the CI for DirectXShaderCompiler and compiled it clang instead of gcc and that resulted in a bit of a size reduction:
`
cmake .. -GNinja -C ../cmake/caches/PredefinedParams.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DENABLE_DXIL2SPV=ON -DLLVM_ENABLE_TERMINFO=OFF
`

> Regarding `libtinfo.so.5`, have you tried https://aur.archlinux.org/packages/ncurses5-compat-libs? I think I may have used it on Arch last time I was testing it. 

I did also check this package just now and it does provide `libtinfo.so.5` which is nice!

**Comment by expenses** [comment]
None of the binaries (DirectXShaderCompiler CI artifacts or compiled by me) are stripped but that's an option if the size really matters

**Review by h3r2tic — APPROVED** [review]
Okays, this size is quite reasonable! Thanks! Will merge after testing on Arch 🙂

**Comment by h3r2tic** [comment]
:partying_face: :tada: that's great, thanks for letting us know :heart: Sounds like an upgrade is in order!

**Comment by MarijnS95** [comment]
Yup, as long as your shaders keep compiling... :grimacing: :cold_sweat:

**Comment by MarijnS95** [comment]
@h3r2tic I see you already started pushing to https://github.com/EmbarkStudios/kajiya/compare/hassle-rs-10, nice stuff (but I don't recall us switching all our ternary if's to `select()`...)! Don't forget to remove the `libtinfo5` dependency from the readme though as per this PR; I double-checked your branch with `ldd` to make sure it is indeed gone!

**Comment by h3r2tic** [comment]
Hah, nice spying @MarijnS95, and thanks for the tip xD I also checked by running `kajiya` on the Steam Deck which doesn't have libtinfo xD (unfortunately the `mesa` driver that the Deck uses crashes hard on ray tracing)

... how did you manage to dodge switching your ternary operators to `select`? That change was so annoying >__<'

**Comment by h3r2tic** [comment]
Maybe you didn't use ternary with vector types?

**Comment by MarijnS95** [comment]
Ouuu, our RayTracing app ran on Steam Deck... half a year ago... in fact I found a `Swapchain` issue that may explain a gamma mismatch **today and was about to retest it** :joy:.

> ... how did you manage to dodge switching your ternary operators to select? That change was so annoying >__<'

What error are you getting? We just... didn't have to do it... but we are on https://github.com/microsoft/DirectXShaderCompiler/commit/0392e60dbc87bf8aa5cbfe826622b517fe39fde0 from Nov 11th so it may have been a more recent change that causes it.

> Maybe you didn't use ternary with vector types?

Just checked and we definitely are. Will keep you posted after pulling in a more recent version, we want to get rid of `ncurses5` as well!

**Comment by h3r2tic** [comment]
> Ouuu, our RayTracing app ran on Steam Deck... half a year ago... in fact I found a `Swapchain` issue that may explain a gamma mismatch **today and was about to retest it** joy.

Wat. I'm getting horrible crashes as soon as I even try and trace shadows :joy: Depending on the `RADV_PERFTEST` env variable I'm either getting a TDR with a few screen blanks, and the app closing down, oooooor the screen flashing white and the whole Deck rebooting :laughing:

> > ... how did you manage to dodge switching your ternary operators to select? That change was so annoying >__<'
> 
> What error are you getting? We just... didn't have to do it... but we are on [microsoft/DirectXShaderCompiler@0392e60](https://github.com/microsoft/DirectXShaderCompiler/commit/0392e60dbc87bf8aa5cbfe826622b517fe39fde0) from Nov 11th so it may have been a more recent change that causes it.

Don't remember the exact text, but basically the error literally told me to use `select`.

Ah, there we go, same as here: https://github.com/GPUOpen-Effects/FidelityFX-FSR/issues/28

> > Maybe you didn't use ternary with vector types?
> 
> Just checked and we definitely are. Will keep you posted after pulling in a more recent version, we want to get rid of `ncurses5` as well!

Hah, then prepare for the same fun I had!

**Comment by MarijnS95** [comment]
> Wat. I'm getting horrible crashes as soon as I even try and trace shadows  Depending on the `RADV_PERFTEST` env variable I'm either getting a TDR with a few screen blanks, and the app closing down, oooooor the screen flashing white and the whole Deck rebooting

Hah, I'll keep you posted whether I can get anything to run... But we do run on phones (Samsung Xclipse 920) too already though :grimacing: (probably need a fresh issue/discussion for this instead of sidetracking here).



> Don't remember the exact text, but basically the error literally told me to use `select`.
> 
> Ah, there we go, same as here: [GPUOpen-Effects/FidelityFX-FSR#28](https://github.com/GPUOpen-Effects/FidelityFX-FSR/issues/28)

Ooooeh, using a vector in the _conditional_ part; I only see us using vectors in the true/false expression bit which should still be fine :grimacing: 

> Hah, then prepare for the same fun I had!

No worries about _fun_. DXC will give me plenty. We're already starting with:

```
bindless.hlsl:110:46: error: variable 'original' is uninitialized when used here [-Werror,-Wuninitialized]
        buffer.InterlockedAdd(offset, value, original);
                                             ^~~~~~~~
bindless.hlsl:109:22: note: initialize the variable 'original' to silence this warning
        uint original;
                     ^
                      = 0
```

https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/interlockedadd the third argument is clearly annotated as `out`, _not_ `inout`, so I don't see why it wants it to be initialized.

**Comment by h3r2tic** [comment]
> Hah, I'll keep you posted whether I can get anything to run... But we do run on phones (Samsung Xclipse 920) too already though grimacing (probably need a fresh issue/discussion for this instead of sidetracking here).

Sounds good, thanks :D


> > Don't remember the exact text, but basically the error literally told me to use `select`.
> > Ah, there we go, same as here: [GPUOpen-Effects/FidelityFX-FSR#28](https://github.com/GPUOpen-Effects/FidelityFX-FSR/issues/28)
> 
> Ooooeh, using a vector in the _conditional_ part; I only see us using vectors in the true/false expression bit which should still be fine grimacing

Yeah, vectors as the conditional part was the fun thing about the old ternary :P

> > Hah, then prepare for the same fun I had!
> 
> No worries about _fun_. DXC will give me plenty. We're already starting with:
> 
> ```
> bindless.hlsl:110:46: error: variable 'original' is uninitialized when used here [-Werror,-Wuninitialized]
>         buffer.InterlockedAdd(offset, value, original);
>                                              ^~~~~~~~
> bindless.hlsl:109:22: note: initialize the variable 'original' to silence this warning
>         uint original;
>                      ^
>                       = 0
> ```
> 
> https://learn.microsoft.com/en-us/windows/win32/direct3dhlsl/interlockedadd the third argument is clearly annotated as `out`, _not_ `inout`, so I don't see why it wants it to be initialized.

That's weird indeed! At least I didn't get any of those :see_no_evil:

**Comment by h3r2tic** [comment]
Closing in favor of #76

**Comment by MarijnS95** [comment]
Nice! Fortunately we're already working with a friendly DXC developer to get the issue fleshed out :)

**Pull request closed without merging**
